### ISSUE TITLE
includes does not work on ie11

### ISSUE THREAD

**Issue by peca11** [jerrylow/breakpoints#1]
Hello!
I just realized your code give an error on ie11 on line 211.
It turns out ie11 does not support "includes" method.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/includes

My Suggestion.

change this:
} else if (compareMethods.includes(method)) {
to this:
} else if (compareMethods.indexOf(method) >= 0) {

thanks

**Comment by jerrylow** [comment]
Thanks @peca11 I will take a look at this soon and test it out.

**Comment by jerrylow** [comment]
Updated and fixed here https://github.com/jerrylow/breakpoints/commit/1c818f712e974f2e7f16d8b25f8282b68048f378
