### ISSUE TITLE
Not working if scrollbar is present

### ISSUE THREAD

**Issue by DavidVonAmri** [jerrylow/breakpoints#2]
So, I'm trying this plugin and from what I can see the width of the breakpoint settings are not correct if there is a scrollbar present. 

If I have the following settings on a page with a scrollbar:

```
breakpoints: [{
    "name": "tablet",
        "width": 768 //will actually detect breakpoint at 785
    }, {
        "name": "desktop",
        "width": 1024 //will actually detect breakpoint at 1041
    }]
```

**Comment by jerrylow** [comment]
Thanks, I've just cut a release `1.8.1` to fix this:

## Without scrollbar

![Screen Recording 2020-12-22 at 11 09 53 AM mov](https://user-images.githubusercontent.com/984430/102925022-80405a80-4447-11eb-860c-b0c3552ca412.gif)

## With scrollbar

![Screen Recording 2020-12-22 at 11 10 46 AM mov](https://user-images.githubusercontent.com/984430/102925033-85050e80-4447-11eb-9e04-618faa7c82a2.gif)
